spring.application.name=senor-turno
spring.data.mongodb.uri=mongodb+srv://admin:GM6VDr5d7EbYQ75a@don-turno-cluster.ld0xsx0.mongodb.net/senorturno?retryWrites=true&w=majority&appName=don-turno-cluster
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html
